site_name: AngusWG Blog
site_description: AngusWG的博客
site_author: AngusWG
site_url: https://anguswg.github.io/AngusWG/
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists

theme: flatly

nav:
  - Home: index.md
  - 随笔:
      - 随笔\好物分享.md
      - 随笔\VR游戏感想.md
  - 项目:
      - 项目\网易云消息推送歌曲收集.md
      - 项目\编程兴趣小组招人.md
  - 编程:
      - 编程\pythoner使用规范.md
      - 编程\Vim笔记.md
  - Python:
      - Python\用pycharm装包出现pycharm The repository located at pypi douban com is not a.md
      - Python\安装mysqlclient报错问题.md
  - About: about.md
