site_name: AngusWG Blog
site_description: AngusWG的博客
site_author: AngusWG
site_url: https://anguswg.github.io/simple_blog/
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

theme: lux

nav:
    - Home: index.md
    - 随笔:
      - 随笔\git设置代理.md
      - 随笔\思维产品课.md
      - 随笔\永久关闭WPS热点、云服务.md
      - 随笔\量化相关.md
      - 随笔\win10 开发环境相关.md
      - 随笔\两台Nginx socketio无法通过.md
      - 随笔\RQPro2.0本地环境与VS code 集成.md
      - 随笔\企业名模糊查询调研.md
      - 随笔\socketio 第三次握手失败问题.md
      - 随笔\cmder 通过跳转机 rz sz 传输文件.md
      - 随笔\如何愉快的魂穿到公司——内网连接指南.md
      - 随笔\conda与rqdatac教程.md
      - 随笔\outlook+jira+to-do.md
      - 随笔\LINK fatal error LNK1158 cannot run 'rc.exe'.md
      - 随笔\一个js破解问题记录.md
      - 随笔\PyCharm及vscode快速配置RQSDK上手 说明文档.md
      - 随笔\pycharm如何同时编辑多行.md
      - 随笔\wsl 上装node.md
      - 随笔\乐理笔记.md
    - 项目:
      - 项目\网易云消息推送歌曲收集.md
      - 项目\编程兴趣小组招人.md
      - 项目\韭菜的股市研究.md
      - 项目\GBI项目知识点.md
    - 编程:
      - 编程\StarUML破解.md
      - 编程\编程方式.md
      - 编程\关于编程.md
      - 编程\centos 重装yum与python.md
      - 编程\python设计资料.md
      - 编程\代替supervisor - gosuv.md
      - 编程\更优雅的生成requirements.txt.md
      - 编程\Sphinx 编译报错nonlocal open_cite_tag.md
      - 编程\国内 github 慢.md
      - 编程\mongodb 排序 根据 _id 插入 测试.md
      - 编程\ss.md
      - 编程\frp 服务器 树莓派 内网穿透.md
      - 编程\树莓派 自动挂载.md
      - 编程\zsh安装.md
      - 编程\树莓派+motion 搭建摄像头监控系统.md
      - 编程\google.protobuf.Timestamp is not defined.md
      - 编程\Jenkins pipeline 构建后发给提交者(触发者)邮件.md
      - 编程\调度算法记录.md
      - 编程\windows上的docker.md
      - 编程\复习笔记.md
    - Python:
      - Python\用pycharm装包出现pycharm The repository located at pypi douban com is not a.md
      - Python\安装mysqlclient报错问题.md
      - Python\python3 - mysql 数据存储性能测试.md
      - Python\解决Flask-SQLAlchemy 2006 MySQL server has gone away 问题.md
      - Python\Python Pypi Server.md
      - Python\在控制台（console）执行python文件、debug python程序.md
      - Python\flask_schedule logging 多进程 问题.md
      - Python\python 时间戳问题.md
      - Python\转 盘点 Python 中的那些冷知识.md
      - Python\flask_admin csv 导出  中文乱码问题.md
      - Python\win10自带Ubuntu使用win10的python方式.md
      - Python\python prometheus gunicorn 多进程解决方案.md
      - Python\python 性能分析.md
      - Python\sqlalchemy 多组条件查询.md
      - Python\flask_babelex 使用.md
      - Python\flask_admin设置宽度为全屏.md
      - Python\flask_admin 主页支持markdown写入.md
      - Python\pip修改为豆瓣源 脚本.md
      - Python\pycharm问题.md
    - About: about.md
